# Generated by Django 6.1.1 on 2026-10-06 05:16

import django.db.models.deletion
import mysteries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Not yet on show'), ('published', 'On show'), ('retired', 'Taken off show')], db_index=True, default='draft', max_length=12)),
                ('is_sample', models.BooleanField(default=False, help_text='Made-up practice material, safe to remove.')),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(help_text='Fingerprint of the original file.', max_length=64, unique=True)),
                ('original_bytes', models.BigIntegerField(default=0)),
                ('original_format', models.CharField(blank=True, max_length=20)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('web_width', models.PositiveIntegerField(default=0)),
                ('web_height', models.PositiveIntegerField(default=0)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Object ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_text', models.CharField(blank=True, help_text='As the catalog gives it, for example "about 1920".', max_length=100, verbose_name='Date')),
                ('catalog', models.JSONField(blank=True, default=dict, help_text='The catalog row this came from, kept as imported.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'mysteries',
                'ordering': ['-published_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=mysteries.models.new_reference, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('accepted', 'Accepted into the record'), ('rejected', 'Declined'), ('withdrawn', 'Withdrawn after acceptance')], db_index=True, default='pending', max_length=12)),
                ('person_name', models.CharField(max_length=200)),
                ('confidence', models.CharField(choices=[('certain', 'I am certain'), ('probable', 'I am fairly sure'), ('possible', 'It is my best guess')], default='probable', max_length=10)),
                ('box_x', models.FloatField(blank=True, null=True)),
                ('box_y', models.FloatField(blank=True, null=True)),
                ('box_w', models.FloatField(blank=True, null=True)),
                ('box_h', models.FloatField(blank=True, null=True)),
                ('position_note', models.CharField(blank=True, max_length=300)),
                ('contributor_name', models.CharField(blank=True, max_length=200)),
                ('contributor_contact', models.CharField(blank=True, max_length=254)),
                ('contact_ok', models.BooleanField(default=False)),
                ('credit_ok', models.BooleanField(default=False)),
                ('personal_data_removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mystery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='mysteries.mystery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('testimony', 'I know from my own knowledge'), ('document', 'I have a document or photograph'), ('cross_reference', 'It matches another record')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('file', models.CharField(blank=True, help_text='Where the uploaded file is kept, inside the data folder.', max_length=300)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('rights_acknowledged', models.BooleanField(default=False)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='mysteries.submission')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeaccessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deaccessions', to='mysteries.submission')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessions', to='mysteries.submission')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
    ]
